/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.cooperstandard.race.frames.panels;

import com.cooperstandard.race.ui.IconThumbSliderUI;
import javax.swing.ImageIcon;

/**
 *
 * @author Tiago
 */
public class CabecalhoPanel extends javax.swing.JPanel {

    /**
     * Creates new form CabecalhoPanel
     */
    public CabecalhoPanel() {
        initComponents();
        ImageIcon imageIcon = new ImageIcon();
        jSlider1.setUI(new IconThumbSliderUI(jSlider1, imageIcon, imageIcon));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpDescricaoCabecalho = new javax.swing.JPanel();
        lbKpi1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lbMeta1 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSlider1 = new javax.swing.JSlider();

        jpDescricaoCabecalho.setBackground(new java.awt.Color(26, 103, 177));
        jpDescricaoCabecalho.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbKpi1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbKpi1.setForeground(new java.awt.Color(255, 255, 255));
        lbKpi1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbKpi1.setText("KPI");

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        lbMeta1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbMeta1.setForeground(new java.awt.Color(255, 255, 255));
        lbMeta1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbMeta1.setText("Turno");

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout jpDescricaoCabecalhoLayout = new javax.swing.GroupLayout(jpDescricaoCabecalho);
        jpDescricaoCabecalho.setLayout(jpDescricaoCabecalhoLayout);
        jpDescricaoCabecalhoLayout.setHorizontalGroup(
            jpDescricaoCabecalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDescricaoCabecalhoLayout.createSequentialGroup()
                .addComponent(lbKpi1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbMeta1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpDescricaoCabecalhoLayout.setVerticalGroup(
            jpDescricaoCabecalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbKpi1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(lbMeta1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jSlider1.setBackground(new java.awt.Color(26, 103, 177));
        jSlider1.setFont(jSlider1.getFont());
        jSlider1.setMajorTickSpacing(10);
        jSlider1.setMaximum(480);
        jSlider1.setPaintLabels(true);
        jSlider1.setPaintTrack(false);
        jSlider1.setValue(0);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpDescricaoCabecalho, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jSlider1, javax.swing.GroupLayout.DEFAULT_SIZE, 479, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpDescricaoCabecalho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSlider1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JPanel jpDescricaoCabecalho;
    private javax.swing.JLabel lbKpi1;
    private javax.swing.JLabel lbMeta1;
    // End of variables declaration//GEN-END:variables
}
