/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.cooperstandard.race.frames.panels;

import com.cooperstandard.race.models.Kpi;
import com.cooperstandard.race.ui.IconThumbSliderUI;
import com.cooperstandard.race.util.ImageUtil;

import javax.swing.*;

/**
 * @author Tiago
 */
public class RacePanelTreeTurns extends javax.swing.JPanel {

    private static final long serialVersionUID = -5407934704880959443L;

    /**
     * Creates new form RacePanel
     */
    public RacePanelTreeTurns(Kpi kpi) {
        initComponents();
        if (kpi != null) {
            kpi.getTurnos().forEach(turno -> {
                JSlider jslider = new JSlider();
                jslider.setMajorTickSpacing(10);
                jslider.setValue(0);
                jslider.setMaximum(kpi.getMeta() != null ? kpi.getMeta().intValue() : 0);
                jslider.setPaintTrack(false);
                lbOee1.setText(kpi.getNome());
                addCinderTrack(jslider, "config/images/cars/".concat(turno.getCarro()));
                setActualValue(jslider, turno.getTotalPontuacao() != null ? turno.getTotalPontuacao().intValue() : 0);
            });
        }
    }

    private void setActualValue(JSlider jslider, Integer value) {
        new Thread(() -> {
            try {
                int v = 0;
                while (v <= value) {
                    jslider.setValue(v);
                    Thread.sleep(2000L);
                    v += 10;
                }
            } catch (Exception ex) {
                ex.printStackTrace();
            }
        }).start();
    }

    public void addCinderTrack(JSlider jslider, String imagePath) {
        ImageIcon imageIcon = ImageUtil.getImageIconFromUserPath(imagePath);
        IconThumbSliderUI iconThumbSliderUI = new IconThumbSliderUI(jslider, imageIcon, imageIcon);
        jslider.setUI(iconThumbSliderUI);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbOee1 = new javax.swing.JLabel();
        lbOeeMeta4 = new javax.swing.JLabel();
        lbOeeMeta5 = new javax.swing.JLabel();
        lbOeeMeta6 = new javax.swing.JLabel();
        jSlider1 = new javax.swing.JSlider();
        jSlider2 = new javax.swing.JSlider();
        jSlider3 = new javax.swing.JSlider();

        lbOee1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbOee1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbOee1.setText("OEE");
        lbOee1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbOeeMeta4.setBackground(new java.awt.Color(255, 0, 0));
        lbOeeMeta4.setFont(new java.awt.Font("Tahoma", 1, 9)); // NOI18N
        lbOeeMeta4.setForeground(new java.awt.Color(255, 255, 255));
        lbOeeMeta4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbOeeMeta4.setText("C");
        lbOeeMeta4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lbOeeMeta4.setOpaque(true);

        lbOeeMeta5.setBackground(new java.awt.Color(255, 255, 0));
        lbOeeMeta5.setFont(new java.awt.Font("Tahoma", 1, 9)); // NOI18N
        lbOeeMeta5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbOeeMeta5.setText("B");
        lbOeeMeta5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lbOeeMeta5.setOpaque(true);

        lbOeeMeta6.setBackground(new java.awt.Color(51, 255, 51));
        lbOeeMeta6.setFont(new java.awt.Font("Tahoma", 1, 9)); // NOI18N
        lbOeeMeta6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbOeeMeta6.setText("A");
        lbOeeMeta6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lbOeeMeta6.setOpaque(true);

        jSlider1.setMajorTickSpacing(10);
        jSlider1.setMaximum(480);
        jSlider1.setPaintTrack(false);
        jSlider1.setValue(0);

        jSlider2.setMajorTickSpacing(10);
        jSlider2.setMaximum(480);
        jSlider2.setPaintTrack(false);
        jSlider2.setValue(0);

        jSlider3.setMajorTickSpacing(10);
        jSlider3.setMaximum(480);
        jSlider3.setPaintTrack(false);
        jSlider3.setValue(0);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lbOee1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(129, 129, 129)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(lbOeeMeta4, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(lbOeeMeta6, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(lbOeeMeta5, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jSlider1, javax.swing.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE)
                                        .addComponent(jSlider2, javax.swing.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE)
                                        .addComponent(jSlider3, javax.swing.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE))
                                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lbOee1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jSlider1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(lbOeeMeta6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jSlider2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(lbOeeMeta5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addGap(0, 0, 0)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(lbOeeMeta4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jSlider3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                .addGap(0, 0, 0))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSlider jSlider1;
    private javax.swing.JSlider jSlider2;
    private javax.swing.JSlider jSlider3;
    private javax.swing.JLabel lbOee1;
    private javax.swing.JLabel lbOeeMeta4;
    private javax.swing.JLabel lbOeeMeta5;
    private javax.swing.JLabel lbOeeMeta6;
    // End of variables declaration//GEN-END:variables
}
